server:
  port: 8081

spring:
  profiles:
    active: dev
---
server:
  port: 8082

spring:
  profiles: dev
---
server:
  port: 8083

spring:
  profiles: prod
---


#  person:
#        age: 20
#        zhiwei: true
#        birth: 2018/10/10
#        maps: {k1: v1,k2: v2}
#        lists: [dog,cat]
#        dog: {name: xiaohuang,age: 2}
#        last-name: zhangsan

